### PR TITLE
PR test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kaadmy** [comment]
I'll try to merge the changes now.
**Edit**: seems you can't specify which commits to merge, might be wrong about that though.

**Comment by ghost** [comment]
So in which commits are you interested? Some of them are for the server (like the suicide command, the locked signs...), and other are personal tastes modifications. Maybe will not fit well in the subgame.

I'll try to make a server branch with my modifications, and merge to master branch only the commits that you want in the subgame. If rubenwardy reads this maybe he knows a better way of doing that.

**Comment by kaadmy** [comment]
I like some of the changes, like the rotated wood nodes.

Some changes, like the welcome mod text, I don't want in master, because it's specific for that one server then.

**Comment by kaadmy** [comment]
I'll close this PR; it's unneeded now.

**Pull request closed without merging**
