### PR TITLE
Bed: Clean up code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by asl97** [comment]
imo, since it's kaadmy repo, you should be following kaadmy coding style.

the repo mostly contain a three space indent, not a tab (although some part of the code has random tabs in them).

changing the indent of just one file just for the sake of changing it isn't a good reason.

**Comment by kaadmy** [comment]
You can re-indent if you want, but the version of the Lua indention scheme for Emacs is kinda crappy and screws up the indentation, it mixes tabs and spaces and indents to uneven levels. I just mash up the code to get it indenting properly.

**Comment by ghost** [comment]
Update.
I re-indented code.

**Comment by kaadmy** [comment]
All right, it seems OK now, merging it.

**Pull request merged**
